package com.medlog.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme
val md_theme_primary = Color(0xFF1B6B4D)
val md_theme_onPrimary = Color(0xFFFFFFFF)
val md_theme_primaryContainer = Color(0xFFA4F5C8)
val md_theme_onPrimaryContainer = Color(0xFF002114)
val md_theme_secondary = Color(0xFF4E6355)
val md_theme_onSecondary = Color(0xFFFFFFFF)
val md_theme_secondaryContainer = Color(0xFFD0E8D6)
val md_theme_onSecondaryContainer = Color(0xFF0B1F14)
val md_theme_tertiary = Color(0xFF3B6471)
val md_theme_onTertiary = Color(0xFFFFFFFF)
val md_theme_tertiaryContainer = Color(0xFFBFEAF8)
val md_theme_onTertiaryContainer = Color(0xFF001F28)
val md_theme_error = Color(0xFFBA1A1A)
val md_theme_onError = Color(0xFFFFFFFF)
val md_theme_errorContainer = Color(0xFFFFDAD6)
val md_theme_onErrorContainer = Color(0xFF410002)
val md_theme_background = Color(0xFFFBFDF8)
val md_theme_onBackground = Color(0xFF191C1A)
val md_theme_surface = Color(0xFFFBFDF8)
val md_theme_onSurface = Color(0xFF191C1A)
val md_theme_surfaceVariant = Color(0xFFDDE5DB)
val md_theme_onSurfaceVariant = Color(0xFF414941)
val md_theme_outline = Color(0xFF717971)
val md_theme_outlineVariant = Color(0xFFC1C9BF)
val md_theme_surfaceContainerLow = Color(0xFFF5F7F2)
val md_theme_surfaceContainer = Color(0xFFEFF1EC)
val md_theme_surfaceContainerHigh = Color(0xFFE9ECE6)
val md_theme_surfaceContainerHighest = Color(0xFFE3E6E0)

// Dark theme
val md_theme_dark_primary = Color(0xFF88D8AD)
val md_theme_dark_onPrimary = Color(0xFF003823)
val md_theme_dark_primaryContainer = Color(0xFF005236)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4F5C8)
val md_theme_dark_secondary = Color(0xFFB4CCBA)
val md_theme_dark_onSecondary = Color(0xFF203528)
val md_theme_dark_secondaryContainer = Color(0xFF374B3E)
val md_theme_dark_onSecondaryContainer = Color(0xFFD0E8D6)
val md_theme_dark_tertiary = Color(0xFFA3CEDC)
val md_theme_dark_onTertiary = Color(0xFF043541)
val md_theme_dark_tertiaryContainer = Color(0xFF224C58)
val md_theme_dark_onTertiaryContainer = Color(0xFFBFEAF8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DE)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BF)
val md_theme_dark_outline = Color(0xFF8B938A)
val md_theme_dark_outlineVariant = Color(0xFF414941)
val md_theme_dark_surfaceContainerLow = Color(0xFF1F2320)
val md_theme_dark_surfaceContainer = Color(0xFF232724)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2D312E)
val md_theme_dark_surfaceContainerHighest = Color(0xFF383C39)

// Semantic colors
val SeverityMild = Color(0xFF4CAF50)
val SeverityModerate = Color(0xFFFF9800)
val SeveritySevere = Color(0xFFF44336)

val MoodGreat = Color(0xFF4CAF50)
val MoodGood = Color(0xFF8BC34A)
val MoodOkay = Color(0xFFFFC107)
val MoodBad = Color(0xFFFF9800)
val MoodTerrible = Color(0xFFF44336)

// Dashboard accent gradients
val GradientStart = Color(0xFF1B6B4D)
val GradientEnd = Color(0xFF2D9B6E)
val GradientStartDark = Color(0xFF005236)
val GradientEndDark = Color(0xFF007A4F)
